# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  pull_request:
    branches: [ my-9.3.0.9-RC ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package install -DskipTests --file pom.xml

    - name: Upload Artifacts 1
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pdi-ce-9.3.0.8-870.zip
        path: /home/runner/work/pentaho-kettle/pentaho-kettle/assemblies/client/target/pdi-ce-9.3.0.8-870.zip

    - name: Upload Artifacts 2
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pdi-core-libs-9.3.0.8-870.zip
        path: /home/runner/work/pentaho-kettle/pentaho-kettle/assemblies/core/lib/target/pdi-core-libs-9.3.0.8-870.zip

    - name: Upload Artifacts 3
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pdi-core-static-9.3.0.8-870.zip
        path: /home/runner/work/pentaho-kettle/pentaho-kettle/assemblies/core/static/target/pdi-core-static-9.3.0.8-870.zip

    - name: Upload Artifacts 4
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pdi-core-ce-9.3.0.8-870.zip
        path: /home/runner/work/pentaho-kettle/pentaho-kettle/assemblies/core/client/target/pdi-core-ce-9.3.0.8-870.zip
